---
  Logging:
    LogLevel:
      Default: Information
      Microsoft: Warning
      Microsoft.Hosting.Lifetime: Information
  AllowedHosts: "*"
  basePath: "/"
  Kestrel:
    Endpoints:
      Http:
        Url: http://0.0.0.0:5000
      HttpsInlineCertFile:
        Url: https://0.0.0.0:5001
